DROP TABLE IF EXISTS links CASCADE;

CREATE TABLE links (
  id VARCHAR(36) PRIMARY KEY,
  originalLink VARCHAR NOT NULL,
  shortToken VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);